services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ../:/workspace:cached

    command: sleep infinity
    
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db-data:/var/lib/mysql
  
  adminer:
    image: adminer
    network_mode: service:db

volumes:
  db-data:
